
services:

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: php8.3-fpm.Dockerfile
    volumes:
      - ./src:/src
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
    ports:
      - 3306:3306